// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pnsfbwzftdtbkwgkvypb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuc2Zid3pmdGR0Ymt3Z2t2eXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MzIxNTgsImV4cCI6MjA4NTEwODE1OH0.kOaHI6oFw-oWokJCkKmUudDyTU4jpESMCnU5wdc3BdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);